*[CG]:  Gradiente Coniugato
*[GDO]: Gradient Domain Operator
*[GF]:  Guided Filter
*[HDR]: ad alto range dinamico
*[LLM]: Local Linear Model
*[LTI]: lineari invarianti alla traslazione
*[MMD]: MultiMarkdown
*[ODF]: OpenDocument
*[PCA]: Principal Component Analysis
*[PSNR]: Peak Signal-to-Noise Ratio
*[SPD]: Distribuzione Spettrale di Potenza
*[SVD]: Singular Value Decomposition
*[SVM]: Support Vector Machine

