LaTeX Input:                 template/mmd-thesis-header
LaTeX Mode:                  memoir
Base Header Level:           2
ToC Depth:                   2
Title:                       Tecniche di miglioramento di immagini basate sulla
                             distribuzione locale del colore
Formatted Title:             Tecniche di miglioramento di immagini
                             basate sulla distribuzione locale del colore
Author:                      Maurizio Zucchelli
Registration Number:         91665
Supervisor:                  Prof. Nicola Adami
Assistant Supervisor:        Prof. Keiichiro Shirai
Second Assistant Supervisor: Prof. Sergio Benini
University:                  Università degli Studi di Brescia
Faculty:                     Dipartimento di Ingegneria dell'Informazione
Course:                      Corso di Laurea Magistrale in Ingegneria Informatica
Academic Year:               2013-2014
BibTeX:                      papers/bibliography.bib
Languages:                   italian
LaTeX Input:                 template/mmd-natbib-plain
LaTeX Input:                 template/mmd-thesis-begin-doc
LaTeX Input:                 mmd-equation-mode
LaTeX Footer:                template/mmd-thesis-footer

<!-- % The empty line is important *in every file* -->
